#!/bin/sh
dir="./files/pulsefix"

if [ ! -d ${dir} ]; then
    mkdir ${dir};
fi

cp pulsefix ${dir}/
cp -r py ${dir}/
cp -r bckp ${dir}/
cp -r tmp ${dir}/

cd ./files
tar -cjf pulsefix.tar.bz2 pulsefix
cd ./..

git add -A
git commit -a
git push -u
